#!/bin/bash
set -e
cd /workspace/repo
git config --global user.email "baca@example.com"
git config --global user.name "BCA Bot"

# Add upstream remote pointing to original repo
git remote add upstream "$ORIGINAL_REPO_URL" || true

# Save original GITHUB_TOKEN for gh pr create
SAVED_GITHUB_TOKEN="${GITHUB_TOKEN}"

# Use COPILOT_TOKEN for copilot if available
export GITHUB_TOKEN="${COPILOT_TOKEN:-$GITHUB_TOKEN}"
baca execute --config "$CONFIG" --work-dir /workspace/repo

echo "------------"
echo " AGENT DONE "
echo "------------"

# Restore original GITHUB_TOKEN for gh pr create and git push
export GITHUB_TOKEN="${SAVED_GITHUB_TOKEN}"

# Create a branch from the current state (after agent changes)
BRANCH_NAME="baca-$(date +%s)-${RANDOM}"
git checkout -b "${BRANCH_NAME}"

# Stage all changes (including new files) before checking
git add -A

# Check if there are any changes (uncommitted or committed on branch)
# Use git rev-list to safely check for new commits (handles unrelated histories)
if git diff --quiet && git diff --cached --quiet && [ "$(git rev-list --count HEAD ^origin/main 2>/dev/null || echo 1)" = "0" ]; then
  echo "No changes made by agent, skipping PR creation"
  exit 0
fi

# Configure git to use GITHUB_TOKEN for authentication
gh auth setup-git
git config --global url."https://oauth2:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

# Get original repo path for PR (from environment variable, not git remote)
ORIGINAL_PATH=$(echo "$ORIGINAL_REPO_URL" | sed -e 's|^https://github.com/||' -e 's|^git@github.com:||' -e 's|\.git$||')

# Get fork owner and repo from the fork URL file (created by fork-setup)
FORK_URL=$(cat /workspace/fork-url.txt)
FORK_OWNER=$(echo "$FORK_URL" | sed -e 's|^https://github.com/||' | cut -d'/' -f1)

# Check if PR metadata was generated by execute wrapper
if [ -f /workspace/pr-metadata.txt ]; then
  echo "Using PR metadata from agent..."
  PR_TITLE=$(grep "^TITLE:" /workspace/pr-metadata.txt | head -1 | sed 's/^TITLE: *//')
  PR_BODY=$(sed -n '/^BODY:/,${/^BODY:/d;p}' /workspace/pr-metadata.txt)
else
  echo "No PR metadata found, using fallback..."
  # Extract prompt without everything after ---
  PROMPT_CLEAN=$(echo "$PROMPT" | sed '/^---$/,$d')
  PR_TITLE="Automated code changes"
  PR_BODY="## Prompt

${PROMPT_CLEAN}"
fi

# Commit any uncommitted changes using PR metadata
if ! git diff --quiet || ! git diff --cached --quiet; then
  git add -A
  git commit -m "${PR_TITLE}

${PR_BODY}"
fi

# Push to fork
git push origin "${BRANCH_NAME}"

# Create pull request from fork to original repo
echo "Creating PR: ${FORK_OWNER}:${BRANCH_NAME} -> ${ORIGINAL_PATH}:main"
gh pr create --repo "${ORIGINAL_PATH}" --head "${FORK_OWNER}:${BRANCH_NAME}" --base main --title "$PR_TITLE" --body "$PR_BODY"
